- platform: group
  name: Living Room climate
  entities:
  - heat.wall_radiator_lr: 22
  - heat.floor_convector_lr: 22

- platform: group
  name: Kitchen climate
  entities:
  - heat.wall_radiator_k: 28

- platform: group
  name: Hall
  entities:
  - heat.floor_heating_h: 29

- platform: group
  name: Bedroom
  entities:
  - heat.wall_radiator: 38
  - combined.air_conditioner: 38
